sudo: required
services:
  - docker

before_install:
  - docker build -t kanorpokpok/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true kanorpokpok/react-test npm test

after_success:
  - docker build -t kanorpokpok/multi-client ./client
  - docker build -t kanorpokpok/multi-nginx ./nginx
  - docker build -t kanorpokpok/multi-server ./server
  - docker build -t kanorpokpok/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin;
  # Take those images and push them to docker hub
  - docker push kanorpokpok/multi-client
  - docker push kanorpokpok/multi-nginx
  - docker push kanorpokpok/multi-server
  - docker push kanorpokpok/multi-worker

